title: Lifestack
email: ashon8813@gmail.com
description: >-
  Thoughts and Experiences
  for Software
baseurl: ""
url: "https://ashon.github.io"

minima:
  social_links:
    github: ashon
    linkedin: ju-won-lee-9662108a
    rss: subscribe

markdown: kramdown
theme: minima
plugins:
- jekyll-feed
- jekyll-archives

jekyll-archives:
  enabled: []
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
