title: Lifestack
email: ashon8813@gmail.com
description: >-
  Thoughts and experiences for software development
baseurl: ""
url: "https://ashon.github.io"
twitter_username:
github_username: ashon

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-toc
