title: Lifestack
email: ashon8813@gmail.com
description: >-
  Thoughts and Experiences
  for Software
baseurl: ""
url: "https://ashon.github.io"

github_username: ashon
linkedin_username: ju-won-lee-9662108a

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
